name: Sync-Images-to-Harbor

run-name: ${{ github.actor }} is Sync Images to Harbor.

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  syncimages:
    runs-on: ubuntu-latest
    steps:
    - name: Use Skopeo Tools Sync Image to Harbor
      run: |
        #!/usr/bin/env bash
        skopeo copy --dest-creds ${{ secrets.HARBOR_CRED }} docker://gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/events:v0.56.5 docker://harbor.flamelephant.com/devops/tekton-releases/github.com/tektoncd/pipeline/cmd/events:v0.56.5
        skopeo copy --dest-creds ${{ secrets.HARBOR_CRED }} docker://gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/resolvers:v0.56.5 docker://harbor.flamelephant.com/devops/tekton-releases/github.com/tektoncd/pipeline/cmd/resolvers:v0.56
        skopeo copy --dest-creds ${{ secrets.HARBOR_CRED }} docker://gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook:v0.56.5 docker://harbor.flamelephant.com/devops/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook:v0.56.5