name: Sync-Images-to-Harbor

run-name: ${{ github.actor }} is Sync Images to Harbor.

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  syncimages:
    runs-on: ubuntu-latest
    steps:
    - name: Use Skopeo Tools Sync Image to Harbor
      run: |
        #!/usr/bin/env bash
        skopeo copy --dest-creds ${{ secrets.HARBOR_CRED }} docker://gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller:v0.56.5 docker://harbor.flamelephant.com/devops/tekton-releases/github.com/tektoncd/pipeline/cmd/controller:v0.56.5
        skopeo copy --dest-creds ${{ secrets.HARBOR_CRED }} docker://gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint:v0.56.5 docker://harbor.flamelephant.com/devops/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint:v0.56.5
        skopeo copy --dest-creds ${{ secrets.HARBOR_CRED }} docker://gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/nop:v0.56.5 docker://harbor.flamelephant.com/devops/tekton-releases/github.com/tektoncd/pipeline/cmd/nop:v0.56.5
        skopeo copy --dest-creds ${{ secrets.HARBOR_CRED }} docker://gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/sidecarlogresults:v0.56.5 docker://harbor.flamelephant.com/devops/tekton-releases/github.com/tektoncd/pipeline/cmd/sidecarlogresults:v0.56.5
        skopeo copy --dest-creds ${{ secrets.HARBOR_CRED }} docker://gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/workingdirinit:v0.56.5 docker://harbor.flamelephant.com/devops/tekton-releases/github.com/tektoncd/pipeline/cmd/workingdirinit:v0.56.5
        skopeo copy --dest-creds ${{ secrets.HARBOR_CRED }} docker://cgr.dev/chainguard/busybox@sha256:19f02276bf8dbdd62f069b922f10c65262cc34b710eea26ff928129a736be791 docker://harbor.flamelephant.com/devops/busybox@sha256:19f02276bf8dbdd62f069b922f10c65262cc34b710eea26ff928129a736be791
        skopeo copy --dest-creds ${{ secrets.HARBOR_CRED }} docker://mcr.microsoft.com/powershell:nanoserver@sha256:b6d5ff841b78bdf2dfed7550000fd4f3437385b8fa686ec0f010be24777654d6 docker://harbor.flamelephant.com/devops/powershell:nanoserver@sha256:b6d5ff8
        skopeo copy --dest-creds ${{ secrets.HARBOR_CRED }} docker://gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/events:v0.56.5 docker://harbor.flamelephant.com/devops/tekton-releases/github.com/tektoncd/pipeline/cmd/events:v0.56.5
        skopeo copy --dest-creds ${{ secrets.HARBOR_CRED }} docker://gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/resolvers:v0.56.5 docker://harbor.flamelephant.com/devops/tekton-releases/github.com/tektoncd/pipeline/cmd/resolvers:v0.56
        skopeo copy --dest-creds ${{ secrets.HARBOR_CRED }} docker://gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook:v0.56.5 docker://harbor.flamelephant.com/devops/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook:v0.56.5