name: Sync-Images-to-Harbor

run-name: ${{ github.actor }} is Sync Images to Harbor.

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  syncimages:
    runs-on: ubuntu-latest
    steps:
    - name: Use Skopeo Tools Sync Image to Harbor
      run: |
        #!/usr/bin/env bash
        skopeo copy --dest-creds ${{ secrets.HARBOR_CRED }} docker://docker.io/library/maven:3-eclipse-temurin-8-focal docker://harbor.flamelephant.com/devops/maven:3-eclipse-temurin-8-focal
        skopeo copy --dest-creds ${{ secrets.HARBOR_CRED }} docker://docker.io/alpine/git:v2.36.1 docker://harbor.flamelephant.com/devops/alpine/git:v2.36.1
        skopeo copy --dest-creds ${{ secrets.HARBOR_CRED }} docker://gcr.dockerproxy.com/kaniko-project/executor:latest docker://harbor.flamelephant.com/devops/kaniko-project/executor:latest

