name: Sync-Images-to-Harbor

run-name: ${{ github.actor }} is Sync Images to Harbor.

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  syncimages:
    runs-on: ubuntu-latest
    steps:
    - name: Use Skopeo Tools Sync Image to Harbor
      run: |
        #!/usr/bin/env bash
        skopeo copy --dest-creds ${{ secrets.HARBOR_CRED }} docker://gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/controller:v0.26.2 docker://harbor.flamelephant.com/devops/tekton-releases/github.com/tektoncd/triggers/cmd/controller:v0.26.2
        skopeo copy --dest-creds ${{ secrets.HARBOR_CRED }} docker://gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/eventlistenersink:v0.26.2 docker://harbor.flamelephant.com/devops/tekton-releases/github.com/tektoncd/triggers/cmd/eventlistenersink:v0.26.2
        skopeo copy --dest-creds ${{ secrets.HARBOR_CRED }} docker://gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/webhook:v0.26.2 docker://harbor.flamelephant.com/devops/tekton-releases/github.com/tektoncd/triggers/cmd/webhook:v0.26.2
        skopeo copy --dest-creds ${{ secrets.HARBOR_CRED }} docker://gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/interceptors:v0.26.2 docker://harbor.flamelephant.com/devops/tekton-releases/github.com/tektoncd/triggers/cmd/interceptors:v0.26.2
        skopeo copy --dest-creds ${{ secrets.HARBOR_CRED }} docker://gcr.io/tekton-releases/github.com/tektoncd/dashboard/cmd/dashboard:v0.32.0 docker://harbor.flamelephant.com/devops/tekton-releases/github.com/tektoncd/dashboard/cmd/dashboard:v0.32.0
        