# 工作流名称
name: Sync-Images-to-DockerHub-Example
# 工作流运行时显示名称
run-name: ${{ github.actor }} is Sync Images to DockerHub.
# 怎样触发工作流
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# 工作流程任务（通常含有一个或多个步骤）
jobs:
  syncimages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Harbor
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.HARBOR_USER }}
        password: ${{ secrets.HARBOR_PASSWORD }}
        logout: false
        
    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
        #!/usr/bin/env bash
        skopeo copy --dest-creds ${{ secrets.HARBOR_CRED }} docker://gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint:v0.61.0@sha256:56da5618bf121a8c7d81e5a7260b38ab614f3e439cc3327c93ca2251773ab43b docker://harbor.flamelephant.com/devops/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint:v0.61.0@sha256:56da5618bf121a8c7d81e5a7260b38ab614f3e439cc3327c93ca2251773ab43b
        skopeo copy --dest-creds ${{ secrets.HARBOR_CRED }} docker://gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/nop:v0.61.0@sha256:a5ce35b36031084455ae2002f7466b7bdaf49c46a9f7f9ec4d2228e262ee146e docker://harbor.flamelephant.com/devops/tekton-releases/github.com/tektoncd/pipeline/cmd/nop:v0.61.0@sha256:a5ce35b36031084455ae2002f7466b7bdaf49c46a9f7f9ec4d2228e262ee146e
        skopeo copy --dest-creds ${{ secrets.HARBOR_CRED }} docker://gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/sidecarlogresults:v0.61.0@sha256:7f458d2460e45b41586730ceb8f683a8ef4ae9699454af2454509527812574dd docker://harbor.flamelephant.com/devops/tekton-releases/github.com/tektoncd/pipeline/cmd/sidecarlogresults:v0.61.0@sha256:7f458d2460e45b41586730ceb8f683a8ef4ae9699454af2454509527812574dd
        skopeo copy --dest-creds ${{ secrets.HARBOR_CRED }} docker://gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/workingdirinit:v0.61.0@sha256:9fcd6e9ecacb2243e5b56bd4c042c2c585fbabf2d49c20d9c09b178ba8876083 docker://harbor.flamelephant.com/devops/tekton-releases/github.com/tektoncd/pipeline/cmd/workingdirinit:v0.61.0@sha256:9fcd6e9ecacb2243e5b56bd4c042c2c585fbabf2d49c20d9c09b178ba8876083
        skopeo copy --dest-creds ${{ secrets.HARBOR_CRED }} docker://cgr.dev/chainguard/busybox@sha256:19f02276bf8dbdd62f069b922f10c65262cc34b710eea26ff928129a736be791 docker://harbor.flamelephant.com/devops/chainguard/busybox@sha256:19f02276bf8dbdd62f069b922f10c65262cc34b710eea26ff928129a736be791
        skopeo copy --dest-creds ${{ secrets.HARBOR_CRED }} docker://mcr.microsoft.com/powershell:nanoserver@sha256:b6d5ff841b78bdf2dfed7550000fd4f3437385b8fa686ec0f010be24777654d6 docker://harbor.flamelephant.com/devops/powershell:nanoserver@sha256:b6d5ff841b78bdf2dfed7550000fd4f3437385b8fa686ec0f010be24777654d6
        skopeo copy --dest-creds ${{ secrets.HARBOR_CRED }} docker://gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/events:v0.61.0@sha256:f41fdd3237151a63bd08cd64d41f214e69bdb6612c4e7cc12230d47ab42caedc docker://harbor.flamelephant.com/devops/tekton-releases/github.com/tektoncd/pipeline/cmd/events:v0.61.0@sha256:f41fdd3237151a63bd08cd64d41f214e69bdb6612c4e7cc12230d47ab42caedc
        skopeo copy --dest-creds ${{ secrets.HARBOR_CRED }} docker://gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/resolvers:v0.61.0@sha256:6566979b2cb4995d0525bc957ee04e5bb2d3405b2fdd52f424c3edca371ca6aa docker://harbor.flamelephant.com/devops/tekton-releases/github.com/tektoncd/pipeline/cmd/resolvers:v0.61.0@sha256:6566979b2cb4995d0525bc957ee04e5bb2d3405b2fdd52f424c3edca371ca6aa
        skopeo copy --dest-creds ${{ secrets.HARBOR_CRED }} docker://gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook:v0.61.0@sha256:9a49179d137025744b85abb46902ad3bce5ec9fa0ff4ee4997a18e74bad2624d docker://harbor.flamelephant.com/devops/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook:v0.61.0@sha256:9a49179d137025744b85abb46902ad3bce5ec9fa0ff4ee4997a18e74bad2624d
 
